// Wraps public/oavg.js (the single browser/Node source of the maths) as a CommonJS module for the API.
import { readFileSync, writeFileSync } from "node:fs";
const src = readFileSync(new URL("../public/oavg.js", import.meta.url), "utf8");
const tail = "})(typeof globalThis !== 'undefined' ? globalThis : (typeof window !== 'undefined' ? window : this));";
if (!src.trimEnd().endsWith(tail)) throw new Error("oavg.js footer changed; update build_api_lib.mjs");
writeFileSync(new URL("../api/_lib/oavg.cjs", import.meta.url),
  "// GENERATED by scripts/build_api_lib.mjs from public/oavg.js - do not edit.\nvar __root = {};\n" +
  src.trimEnd().slice(0, -tail.length) + "})(__root);\nmodule.exports = __root.OAVG;\n");
console.log("wrote api/_lib/oavg.cjs");
